export enum EventCategory {
    CONFERENCE = 'Conference',
    WORKSHOP = 'Workshop',
    CONCERT = 'Concert',
    SEMINAR = 'Seminar',
    EXHIBITION = 'Exhibition',
    FESTIVAL = 'Festival',
    WEBINAR = 'Webinar',
    NETWORKING = 'Networking',
    COMPETITION = 'Competition',
    FUNDRAISER = 'Fundraiser',
    MUSIC = 'Music',
    DRAMA = 'Drama',
    SPORTS = 'Sports',
    COMEDY = 'Comedy',
    ART = 'Art',
}
